/** Auth Actions */
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

/** Categories Actions */
export const CATEGORIES_PENDING = "CATEGORIES_PENDING";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_CATEGORY_BY_ID_SUCCESS = "GET_CATEGORY_BY_ID_SUCCESS";
export const GET_CATEGORY_BY_ID_ERROR = "GET_CATEGORY_BY_ID_ERROR";

/** Users Actions */
export const USERS_PENDING = "USERS_PENDING";
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

/** Questions Actions */
export const QUESTIONS_PENDING = "QUESTIONS_PENDING";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";

export const GET_QUESTIONS_BY_CATEGORY = "GET_QUESTIONS_BY_CATEGORY";
export const GET_QUESTIONS_BY_CATEGORY_SUCCESS =
  "GET_QUESTIONS_BY_CATEGORY_SUCCESS";
export const GET_QUESTIONS_BY_CATEGORY_ERROR =
  "GET_QUESTIONS_BY_CATEGORY_ERROR";

export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
export const GET_QUESTION_BY_ID_SUCCESS = "GET_QUESTION_BY_ID_SUCCESS";
export const GET_QUESTION_BY_ID_ERROR = "GET_QUESTION_BY_ID_ERROR";

export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_ERROR = "ADD_QUESTION_ERROR";

/** Answers Actions */
export const ANSWERS_PENDING = "ANSWERS_PENDING";
export const GET_ANSWERS_BY_QUESTION = "GET_ANSWERS_BY_QUESTION";
export const GET_ANSWERS_BY_QUESTION_SUCCESS =
  "GET_ANSWERS_BY_QUESTION_SUCCESS";
export const GET_ANSWERS_BY_QUESTION_ERROR = "GET_ANSWERS_BY_QUESTION_ERROR";
